source "https://rubygems.org"

gem "rack", "~>2.2.6.2"
gem "sinatra", "~>2.2"

group :test do
  gem "rack-test"
  gem "rest-client"
  gem "rspec"
  gem "rspec_junit_formatter"
  gem "rubysl-securerandom"
end
